services:
  bookstore:
    build: bookstore
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:mysql://bookstore-db:3306/book_store?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: admin
    restart: always
    depends_on:
      bookstore-db:
        condition: service_healthy

  bookstore-db:
    image: mysql:8.0.33 
    ports:
      - "3307:3306" # Este puerto es para acceder desde el host
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: book_store
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

